sytnhetic data pipline added
LRyba/PJA_ASI_12c_GR3 pull request #13
Opened 2024-06-01 15:25 UTC by LRyba

2024-06-01 15:52 UTC, git3st commented
daje approve ale z poprzedniego pr zmiany trzeba dodac

2024-06-01 15:52 UTC, git3st approved these changes

2024-06-18 22:38 UTC, pcwieka requested changes

2024-06-18 22:38 UTC, pcwieka commented on src/pja_asi_12c_gr3/pipelines/data_preparation/pipeline.py
> +            inputs=["synthetic_data if params:use_synthetic_data else obesity_data", "params:cleaning.cols_to_remove"],
to wyrażenie w inputs nie jest wspierane w kedro, przynajmniej ja dostaję błąd

2024-06-18 22:38 UTC, pcwieka commented on src/pja_asi_12c_gr3/pipelines/synthetic_data_generation/nodes.py
> +from sdv.tabular import CTGAN
sdv.tabular nie istnieje w użytej wersji sdv

2024-06-28 13:29 UTC, merged